const data = [
    {
      name:"Alt",
      specialite:"Biochimie",
      match:false,
      id:Math.random()
    },
    {
      name:"blt",
      specialite:"Biochimie",
      match:false,
      id:Math.random()
    },
    {
      name:"blt",
      specialite:"Immunologie",
      match:false,
      id:Math.random()
    },
    {
      name:"blt",
      specialite:"Immunologie",
      match:false,
      id:Math.random()
    },
    {
      name:"blt",
      specialite:"Immunologie",
      match:false,
      id:Math.random()
    },
    {
      name:"blt",
      specialite:"Immunologie",
      match:false,
      id:Math.random()
    },
    {
        name:"blt",
        specialite:"Immunologie",
        match:false,
        id:Math.random()
      },
      {
        name:"blt",
        specialite:"Immunologie",
        match:false,
        id:Math.random()
      },
      {
        name:"blt",
        specialite:"Immunologie",
        match:false,
        id:Math.random()
      },
      {
        name:"blt",
        specialite:"Immunologie",
        match:false,
        id:Math.random()
      },
      {
        name:"Alt",
        specialite:"Biochimie",
        match:false,
        id:Math.random()
      },
      {
        name:"blt",
        specialite:"Biochimie",
        match:false,
        id:Math.random()
      },
      {
        name:"blt",
        specialite:"Immunologie",
        match:false,
        id:Math.random()
      },
      {
        name:"blt",
        specialite:"Immunologie",
        match:false,
        id:Math.random()
      },
      {
        name:"blt",
        specialite:"Immunologie",
        match:false,
        id:Math.random()
      },
      {
        name:"blt",
        specialite:"Immunologie",
        match:false,
        id:Math.random()
      },
      {
          name:"blt",
          specialite:"Immunologie",
          match:false,
          id:Math.random()
        },
        {
          name:"blt",
          specialite:"Immunologie",
          match:false,
          id:Math.random()
        },
        {
          name:"blt",
          specialite:"Immunologie",
          match:false,
          id:Math.random()
        },
        {
          name:"clt",
          specialite:"Immunologie",
          match:false,
          id:Math.random()
        },
  ]
  export default data